version: '3.7'
services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - front
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  front:
    image: tasks-app-front
    build: ./client
    depends_on:
      - back
    networks:
      - frontend

  back:
    image: tasks-app-back
    build: ./server
    networks:
      - frontend
      - backend
networks:
  frontend: {}
  backend: {}
